<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Agnea Sofi Malika">
<meta name="dcterms.date" content="2024-01-19">

<title>Pengaruh Upah Minimum terhadap daya beli di Provinsi Jawa Timur</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Upah Minimum terhadap daya beli di Provinsi Jawa Timur</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Agnea Sofi Malika </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 19, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Provinsi Jawa Timur adalah salah satu provinsi terbesar di Indonesia, baik dari segi luas wilayah, jumlah penduduk, maupun perekonomian. Pada tahun 2023, Provinsi Jawa Timur mencatatkan pertumbuhan ekonomi sebesar 4,95% (yoy), lebih tinggi dari pertumbuhan ekonomi nasional sebesar 4,4% (yoy). Namun, provinsi Jawa Timur juga menghadapi tantangan dalam hal ketimpangan sosial, ketenagakerjaan, dan kemiskinan.</p>
<p>Salah satu isu yang relevan dengan kondisi perekonomian dan kesejahteraan masyarakat di Provinsi Jawa Timur adalah upah minimum. Pada tahun 2023, Gubernur Jawa Timur menetapkan upah minimum provinsi (UMP) sebesar Rp 2.040.244,30, naik 7,8% dari tahun sebelumnya. Selain itu, terdapat perbedaan upah minimum kabupaten/kota (UMK) di 38 kabupaten/kota di Provinsi Jawa Timur, yang berkisar antara Rp 2.114.335,27 hingga Rp 4.525.479,19. Penetapan upah minimum ini tentu berdampak pada daya beli masyarakat di Provinsi Jawa Timur, baik secara positif maupun negatif.</p>
<p>Berdasarkan uraian di atas, maka penelitian ini bertujuan untuk menganalisis pengaruh upah minimum terhadap daya beli di Provinsi Jawa Timur. Penelitian ini diharapkan dapat memberikan kontribusi bagi pengembangan ilmu ekonomi, khususnya mengenai dampak upah minimum terhadap perekonomian daerah. Selain itu, penelitian ini juga diharapkan dapat memberikan masukan bagi pemerintah, pekerja, dan pengusaha dalam menentukan kebijakan upah minimum yang adil dan efisien.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Ada dua variabel yang digunakan sebagai objek penelitian, yaitu daya beli dan upah minimum kota dan kabupaten Jawa Timur. Dalam penelitian ini peneliti menggunakan Badan Pusat Statistik (BPS) untuk mendapatkan data daya beli di Provinsi Jawa Timur tahun 2023, selain itu data dari upah minimum Provinsi Jawa Timur tahun 2023 diambil dari “Keputusan Gubernur Jawa Timur Nomor 188/606/KPTS/013/2022”.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="A">
<li><p>Apakah upah minimum mempengaruhi daya beli di provinsi jawa timur?</p></li>
<li><p>Bagaimana hubungan antara upah minimum dan daya beli di Provinsi Jawa Timur?</p></li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Mengidentifikasi efek dari kenaikan upah minimum terhadap daya beli masyarakat dan perekonomian di wilayah tersebut adalah tujuan utama dari penelitian ini. Penelitian ini dapat membantu pemerintah dan masyarakat dalam merumuskan kebijakan yang tepat terkait upah minimum dan daya beli. Selain itu, penelitian ini juga dapat membantu dalam memperbaiki kondisi ekonomi di Provinsi Jawa Timur dengan meningkatkan daya beli masyarakat dan mengurangi kemiskinan.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(writexl)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p><strong>Upah Minimum</strong></p>
<p>Upah minimum adalah standar penghasilan minimum yang harus diterima oleh pekerja untuk memenuhi kebutuhan hidup yang layak. Upah minimum bertujuan untuk melindungi pekerja dari eksploitasi dan kemiskinan, serta meningkatkan kesejahteraan dan produktivitas pekerja. Namun, upah minimum dapat juga memberikan dampak negatif kepada perekonomian, seperti menimbulkan pengangguran, inflasi, dan penurunan daya saing. Upah minimum ini ditetapkan berdasarkan kondisi ekonomi dan ketenagakerjaan yang menggunakan data dari Badan Pusat Statistik (BPS). Sejak UU Cipta Kerja terbit, penetapan upah minimum menggunakan formula yang mempertimbangkan variable pertumbuhan ekonomi, inflasi, dan indeks tertentu. Gubrenur wajib menetapkan upah minimum provinsi (UMP) dan dapat menetapkan upah minimum kabupaten/kota (UMK) jika hasil perhitungan UMK lebih tinggi daripada UMP.</p>
<p><strong>Daya Beli</strong></p>
<p>Daya beli adalah kemampuan masyarakat untuk membeli barang dan jasa dengan pendapatan yang dihasilkannya. Daya beli sendiri dipengaruhi oleh beberapa factor, seperti tingkat harga, pendapatan, pajak, tabungan, dan kredit. Daya beli berpengaruh terhadap pertumbuhan ekonomi, karena semakin tinggi daya beli masyarakat, semakin tinggi pula permintaan dan konsumsi barang dan jasa yang akan mendorong produksi dan investasi. Dalam meningkatkan daya beli masyarakat diperlukan peran dari pemerintah dan sector swasta. Beberapa upaya yang dapat dilakukan dalam meningkatkan daya beli masyarakat, seperti menjaga stabilitas harga dan jasa, meningkatkan pendapatan masyarakat, memberikan insentif fiscal dan moneter untuk mendorong konsumsi dan investasi, meningkatkan akses masyarakat terhadap pendidikan, kesehatan, dan infrastruktur, serta mendorong diversifikasi ekonomi dan investasi asing.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<colgroup>
<col style="width: 2%">
<col style="width: 26%">
<col style="width: 22%">
<col style="width: 23%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Kabupaten/Kota</th>
<th>Upah.Minimum(Rp)</th>
<th>Tingkat Daya Beli(Rp)</th>
<th>x</th>
<th>y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Kota Surabaya</td>
<td>4.525.479,19</td>
<td>3.517.000,00</td>
<td>6,655664572</td>
<td>6,546172368</td>
</tr>
<tr class="even">
<td>2</td>
<td>Kabupaten Gresik</td>
<td>4.522.030,51</td>
<td>3.513.000,00</td>
<td>6,655333488</td>
<td>6,54567815</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Kabupaten Sidoarjo</td>
<td>4.518.581,85</td>
<td>3.509.000,00</td>
<td>6,655002154</td>
<td>6,545183368</td>
</tr>
<tr class="even">
<td>4</td>
<td>Kabupaten Pasuruan</td>
<td>4.515.133,19</td>
<td>3.506.000,00</td>
<td>6,654670566</td>
<td>6,544811912</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Kabupaten Mojokerto</td>
<td>4.504.787,17</td>
<td>3.495.000,00</td>
<td>6,653674277</td>
<td>6,54344718</td>
</tr>
<tr class="even">
<td>6</td>
<td>Kabupaten Malang</td>
<td>3.268.275,36</td>
<td>2.538.000,00</td>
<td>6,51431864</td>
<td>6,404491618</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Kota Malang</td>
<td>3.194.143,98</td>
<td>2.478.000,00</td>
<td>6,504354489</td>
<td>6,394101302</td>
</tr>
<tr class="even">
<td>8</td>
<td>Kota Pasuruan</td>
<td>3.038.837,64</td>
<td>2.358.000,00</td>
<td>6,482707497</td>
<td>6,372543801</td>
</tr>
<tr class="odd">
<td>9</td>
<td>Kota Batu</td>
<td>3.030.367,09</td>
<td>2.350.000,00</td>
<td>6,481495241</td>
<td>6,371067862</td>
</tr>
<tr class="even">
<td>10</td>
<td>Kabupaten Jombang</td>
<td>2.854.095,88</td>
<td>2.214.000,00</td>
<td>6,455468559</td>
<td>6,345177617</td>
</tr>
<tr class="odd">
<td>11</td>
<td>Kabupaten Probolinggo</td>
<td>2.753.265,95</td>
<td>2.136.000,00</td>
<td>6,439848164</td>
<td>6,329601248</td>
</tr>
<tr class="even">
<td>12</td>
<td>Kabupaten Tuban</td>
<td>2.739.224,88</td>
<td>2.124.000,00</td>
<td>6,437627688</td>
<td>6,327154512</td>
</tr>
<tr class="odd">
<td>13</td>
<td>Kota Mojokerto</td>
<td>2.710.452,36</td>
<td>2.100.000,00</td>
<td>6,433041778</td>
<td>6,322219295</td>
</tr>
<tr class="even">
<td>14</td>
<td>Kabupaten Lamongan</td>
<td>2.701.977,27</td>
<td>2.093.000,00</td>
<td>6,431681691</td>
<td>6,320769228</td>
</tr>
<tr class="odd">
<td>15</td>
<td>Kota Probolinggo</td>
<td>2.576.240,63</td>
<td>1.998.000,00</td>
<td>6,410986425</td>
<td>6,300595484</td>
</tr>
<tr class="even">
<td>16</td>
<td>Kabupaten Jember</td>
<td>2.555.662,91</td>
<td>1.981.000,00</td>
<td>6,40750357</td>
<td>6,296884476</td>
</tr>
<tr class="odd">
<td>17</td>
<td>Kabupaten Banyuwangi</td>
<td>2.528.899,12</td>
<td>1.960.000,00</td>
<td>6,402931505</td>
<td>6,292256071</td>
</tr>
<tr class="even">
<td>18</td>
<td>Kota Kediri</td>
<td>2.318.116,63</td>
<td>1.797.000,00</td>
<td>6,365135283</td>
<td>6,254548077</td>
</tr>
<tr class="odd">
<td>19</td>
<td>Kabupaten Bojonegoro</td>
<td>2.279.568,07</td>
<td>1.767.000,00</td>
<td>6,357852565</td>
<td>6,24723655</td>
</tr>
<tr class="even">
<td>20</td>
<td>Kabupaten Kediri</td>
<td>2.243.422,93</td>
<td>1.740.000,00</td>
<td>6,350911154</td>
<td>6,240549248</td>
</tr>
<tr class="odd">
<td>21</td>
<td>Kota Blitar</td>
<td>2.239.024,44</td>
<td>1.737.000,00</td>
<td>6,350058834</td>
<td>6,239799818</td>
</tr>
<tr class="even">
<td>22</td>
<td>Kabupaten Tulungagung</td>
<td>2.229.358,67</td>
<td>1.729.000,00</td>
<td>6,348179945</td>
<td>6,237794993</td>
</tr>
<tr class="odd">
<td>23</td>
<td>Kabupaten Blitar</td>
<td>2.215.071,18</td>
<td>1.718.000,00</td>
<td>6,345387687</td>
<td>6,235023159</td>
</tr>
<tr class="even">
<td>24</td>
<td>Kabupaten Lumajang</td>
<td>2.200.607,20</td>
<td>1.707.000,00</td>
<td>6,34254253</td>
<td>6,232233521</td>
</tr>
<tr class="odd">
<td>25</td>
<td>Kota Madiun</td>
<td>2.190.216,37</td>
<td>1.700.000,00</td>
<td>6,340487021</td>
<td>6,230448921</td>
</tr>
<tr class="even">
<td>26</td>
<td>Kabupaten Sumenep</td>
<td>2.176.819,94</td>
<td>1.689.000,00</td>
<td>6,337822507</td>
<td>6,22762965</td>
</tr>
<tr class="odd">
<td>27</td>
<td>Kabupaten Nganjuk</td>
<td>2.167.007,05</td>
<td>1.682.000,00</td>
<td>6,335860324</td>
<td>6,225825991</td>
</tr>
<tr class="even">
<td>28</td>
<td>Kabupaten Ngawi</td>
<td>2.158.844,59</td>
<td>1.676.000,00</td>
<td>6,33422138</td>
<td>6,224274014</td>
</tr>
<tr class="odd">
<td>29</td>
<td>Kabupaten Pacitan</td>
<td>2.157.270,25</td>
<td>1.675.000,00</td>
<td>6,333904554</td>
<td>6,224014811</td>
</tr>
<tr class="even">
<td>30</td>
<td>Kabupaten Bondowoso</td>
<td>2.154.504,13</td>
<td>1.673.000,00</td>
<td>6,333347331</td>
<td>6,223495941</td>
</tr>
<tr class="odd">
<td>31</td>
<td>Kabupaten Madiun</td>
<td>2.154.251,34</td>
<td>1.673.000,00</td>
<td>6,333296372</td>
<td>6,223495941</td>
</tr>
<tr class="even">
<td>32</td>
<td>Kabupaten Magetan</td>
<td>2.153.062,37</td>
<td>1.672.000,00</td>
<td>6,333056611</td>
<td>6,223236273</td>
</tr>
<tr class="odd">
<td>33</td>
<td>Kabupaten Bangkalan</td>
<td>2.152.450,83</td>
<td>1.671.000,00</td>
<td>6,332933239</td>
<td>6,22297645</td>
</tr>
<tr class="even">
<td>34</td>
<td>Kabupaten Ponorogo</td>
<td>2.149.709,45</td>
<td>1.669.000,00</td>
<td>6,332379766</td>
<td>6,222456337</td>
</tr>
<tr class="odd">
<td>35</td>
<td>Kabupaten Trenggalek</td>
<td>2.139.426,01</td>
<td>1.661.000,00</td>
<td>6,330297271</td>
<td>6,220369632</td>
</tr>
<tr class="even">
<td>36</td>
<td>Kabupaten Situbondo</td>
<td>2.137.025,85</td>
<td>1.659.000,00</td>
<td>6,329809776</td>
<td>6,219846386</td>
</tr>
<tr class="odd">
<td>37</td>
<td>Kabupaten Pamekasan</td>
<td>2.133.655,03</td>
<td>1.657.000,00</td>
<td>6,329124204</td>
<td>6,219322508</td>
</tr>
<tr class="even">
<td>38</td>
<td>Kabupaten Sampang</td>
<td>2.114.335,27</td>
<td>1.640.000,00</td>
<td>6,325173854</td>
<td>6,214843848</td>
</tr>
</tbody>
</table>
<p>Data yang digunakan berupa data upah minimum dan tingkat daya beli kota dan kabupaten di Jawa Timur tahun 2023. Kemudian data diolah dengan melakukan log pada kedua variabel, sehingga menghasilkan variabel x sebagai upah minimum dan variabel y sebagai tingkat daya beli. Data-data inilah yang nantinya akan digunakan sebagai objek dalam penelitian ini.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>alika<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/metodologipenelitian/dataalika/alika.xlsx"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(alika)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  `Kabupaten/Kota`    `Upah Minimum (Rp)` `Tingkat Daya Beli (Rp)`     x     y
  &lt;chr&gt;                             &lt;dbl&gt;                    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 Kota Surabaya                  4525479.                  3517000  6.66  6.55
2 Kabupaten Gresik               4522031.                  3513000  6.66  6.55
3 Kabupaten Sidoarjo             4518582.                  3509000  6.66  6.55
4 Kabupaten Pasuruan             4515133.                  3506000  6.65  6.54
5 Kabupaten Mojokerto            4504787.                  3495000  6.65  6.54
6 Kabupaten Malang               3268275.                  2538000  6.51  6.40</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-mpg</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Hubungan tingkat daya beli dan upah minimum Jawa Timur tahun 2023"</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>alika,<span class="fu">aes</span>(<span class="at">x=</span>x,<span class="at">y=</span>y))<span class="sc">+</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"#5F9EA0"</span>,<span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"hubungan tingkat daya beli dan upah minimum Jawa Timur"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"upah minimum"</span>,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"daya beli"</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"sumber: Badan Pusat Statistik, Keputusan Gubernur Jawa Timur Nomor 188/606/KPTS/013/2023"</span>)<span class="sc">+</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Dalam penelitian pengaruh upah minimum terhadap daya beli di Provinsi Jawa Timur, menerapkan metode regresi univariat. Metode ini digunakan untuk mengetahui hubungan antara satu variabel bebas dan satu variabel terikat. Dengan menggunakan metode regresi univariat, peneliti dapat mengetahui seberapa besar pengaruh upah minimum terhadap daya beli di Provinsi Jawa Timur. Spesifikasi sebagai berikut:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah upah minimum dan <span class="math inline">\(x_t\)</span> adalah daya beli.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Rangkuman hasil:</p>
<table class="table">
<thead>
<tr class="header">
<th>Coefficients</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>t value</th>
<th>Pr(&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>-0.1142341</td>
<td>0.0032091</td>
<td>-35.6</td>
<td>&lt;2e-16 ***</td>
</tr>
<tr class="even">
<td>x</td>
<td>1.0006332</td>
<td>0.0005001</td>
<td>2000.8</td>
<td>&lt;2e-16 ***</td>
</tr>
</tbody>
</table>
<p>Hasil dimasukkan ke dalam rumus persamaan dan menghasilkan:</p>
<p><span class="math display">\[
y_{t}=\ -0.1142341 + \ 1.0006332x +\mu_t
\]</span></p>
<p>Dari hasil tersebut, dapat disimpulkan bahwa terdapat hubungan positif antara variabel x dan y. Hal ini dapat dilihat dari nilai koefisien regresi sebesar 1.5467 yang bernilai positif. Maka apabila variabel x (upah minimum) naik satu, akan meningkatkan variabel y (daya beli) sebesar 1.0006332.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresi:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>alika<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"alika.xlsx"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>alika)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = alika)

Residuals:
       Min         1Q     Median         3Q        Max 
-7.511e-04 -1.974e-04 -4.032e-05  2.804e-04  5.273e-04 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.1142341  0.0032091   -35.6   &lt;2e-16 ***
x            1.0006332  0.0005001  2000.8   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.0003322 on 36 degrees of freedom
Multiple R-squared:      1, Adjusted R-squared:      1 
F-statistic: 4.003e+06 on 1 and 36 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Multiple R-squared adalah 1,yang berarti bahwa 100% variasi variabel y dapat dijelaskan oleh variabel x. Ini menunjukkan bahwa model regresi memiliki kualitas yang sangat baik. Nilai residual standar error adalah 0.0003322, yang berarti bahwa rata-rata selisih antara nilai y yang sebenarnya dan nilai y yang diprediksi oleh model regresi adalah 0.0003322. Ini menunjukkan bahwa model regresi memiliki tingkat akurasi yang sangat tinggi. Nilai F-statistik adalah 4.003e+06 dan nilai p-value adalah &lt; 2.2e-16, yang berarti bahwa variabel x secara signifikan mempengaruhi variabel y.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>hasil dari penelitian ini membuktikan bahwa peningkatan upah minimum dapat meningkatkan daya beli Masyarakat di Provinsi Jawa Timur tahun 2023, hal ini dapat disebabkan karena pekerja akan memiliki lebih banyak uang untuk dibelanjakan. Hal ini dapat meningkatkan permintaan barang dan jasa, sehingga dapat mendorong pertumbuhan ekonomi. Selain itu, peningkatan upah minimum juga dapat meningkatkan kesejahteraan pekerja, karena mereka dapat memenuhi kebutuhan hidup mereka dengan lebih baik.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Amisa, Y. D., &amp; Waryanto, R. B. D. (2020). PENGARUH UPAH MINIMUM DAN DAYA BELI MASYARAKAT SETIAP PROVINSI TERHADAP KENAIKAN PENGHASILAN TIDAK KENA PAJAK (PTKP) PPH PASAL 21 DI INDONESIA. Majalah Ekonomi, 25(2), 19-27.</p>
<p>Silvia, D., Balafif, M., &amp; Rahmasari, A. (2021). Faktor-Faktor yang Mempengaruhi Tingkat Daya Beli Masyarakat di Kabupaten Sidoarjo. Bharanomics, 2(1), 81-92.</p>
<p>Wihastuti, L., &amp; Rahmatullah, H. (2018). Upah minimum provinsi (UMP) dan penyerapan tenaga kerja di Pulau Jawa. Jurnal Gama Societa, 1(1), 96-102.</p>
<p>Hernaningsih, F. (2018). Pengaruh Kestabilan Inflasi Dan Ketimpangan Pendapatan Terhadap Daya Beli Masyarkat. Jurnal Ilmiah M-Progress, 8(2).</p>
<p>MUZAKI, F. (2018). Pengaruh Pendapatan dan Tingkat Harga Jual Produk Terhadap Daya Beli Masyarakat Muslim (Pada UD Santoso di Klaten Desa Tegalrejo Kec. Rejotangan Kab. Tulungagung).</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>